name: Build TOU Mira

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore TownOfUs/TownOfUsMira.csproj

    - name: Build project
      run: dotnet build TownOfUs/TownOfUsMira.csproj -c Release -o out

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TOU-Mira-Build
        path: out/
